services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile.dev
    environment:
      NODE_ENV: development
      CLIENT_ORIGIN: http://localhost:5173
    command: sh -c "npx prisma generate && npm run dev"
    ports:
      - "4000:4000"
    volumes:
      - ../backend:/app
      - backend-node-modules:/app/node_modules

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile.dev
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - frontend-node-modules:/app/node_modules

volumes:
  backend-node-modules:
  frontend-node-modules:
